version: '3'
services:
  postgres:
    container_name: diario-api
    image: postgres:17
    environment:
      POSTGRES_USER: diario_api
      POSTGRES_PASSWORD: diario_api
      POSTGRES_DB: diario_api
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    ports:
      - '2345:5432'
    restart: unless-stopped
#volumes:
#  postgres-data:
